### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by idealadarsh** [idealadarsh/Mensuration#10]
Please check the build log for detailed information:
https://travis-ci.org/idealadarsh/Mensuration/builds/288887119

**Comment by smsunarto** [comment]
You are missing the license files.
https://developer.android.com/studio/intro/update.html#download-with-gradle

**Comment by JeffreyCA** [comment]
I have opened a PR: #11, which should fix this. The PR build is not passing though, might be due to encryption key.

**Comment by JeffreyCA** [comment]
Now the error is about Lint warnings, you can either fix them or disable abort on error.

**Comment by idealadarsh** [comment]
Builds are passing, I think this can be closed now.
